### PR TITLE
Add option to include runtime and provided

### LINKED ISSUE #60: Add support for runtime and provided dependencies at same time
As discussed here http://stackoverflow.com/questions/6418414/maven-exec-plugin-cant-depend-on-provided-dependancy#comment48129503_16042080 there is no way to use the plugin while getting both provided and runtime dependencies onto the classpath.

### PR DESCRIPTION
**Pull request by rehevkor5**
- New "provided" value for classpathScope includes both runtime and
  provided dependencies
- Closes #60

### CODE REVIEW

**Comment by rehevkor5** [comment]
I can't figure out how to view the log files about the failures. Does anyone else know how? The integration tests succeed when I run them locally.

**Comment by rehevkor5** [comment]
Seems like Travis is not downloading dependencies of the new IT projects. Not sure why.

**Comment by rehevkor5** [comment]
@khmarbaise what do you think of this?

**Comment by rehevkor5** [comment]
Rebased changes and fixed merge conflicts.

The build failed because it ran out of time.

**Review by slawekjaranowski — APPROVED** [review]

**Pull request merged**
