### PR TITLE
[FIXED Issue#18] Spawn non-blocking

### PR DESCRIPTION
**Pull request by demonfiddler**
- exec:exec now has boolean async and asyncDestroyOnShutdown properties
- integration test for the above
- fix existing unit test so that it runs on Windows!!!

### CODE REVIEW

**Comment by demonfiddler** [comment]
@khmarbaise Given that 3rd party POM dependencies typically specify release versions not snapshots, how is an installation to obtain access to the new functionality other than by a version bump? As a relative Maven newbie here may well be some aspect of the release workflow of which I am unaware that would answer this concern but I would appreciate your comments.

I see that on Travis the new 'async' integration test has failed on all three OpenJDK builds. Needless to say, this test passes fine on Windows 8 + Oracle JDK 1.7. I shall attempt to reproduce these failures locally and fix whatever the problem is,

**Comment by khmarbaise** [comment]
You have seen that the CI build has failed? (Travis)?

**Comment by demonfiddler** [comment]
Yes Karl - my previous comment refers to the failure and asks your advice on debugging it. It's entirely unclear what caused the failure - .../target/it/async/build.log seems inaccessible.

**Comment by demonfiddler** [comment]
Closing for now, as I have just discovered that the modified async integration test is now failing under Windows!

**Pull request closed without merging**
