### PR TITLE
Search for exact filename only if executable contains a '.' 

### PR DESCRIPTION
**Pull request by KriKroff**
This PR is a fix for issue #42 due to commit [caec11231e0c3a2e9ee9ed5a40e0e2ccbc831795](https://github.com/mojohaus/exec-maven-plugin/commit/caec11231e0c3a2e9ee9ed5a40e0e2ccbc831795#diff-c835a6e13547a5cbc62133e3801f7920)

Now, a file without a '.' cannot be considered as a possible executable. The 
The behaviour is still not the same as version 1.4.0 but this should be a problem.

### CODE REVIEW

**Comment by khmarbaise** [comment]
Can you please check this PR cause it produces conflicts furthermore i don't see any tests for it?

**Comment by mkarg** [comment]
Won't this imply problems on Linux, where you can have scripts with no dot-extension?

**Comment by khmarbaise** [comment]
Can you please rebase this PR against current master and please squash it to get a single commit as PR...

**Comment by KriKroff** [comment]
I close the PR, PR #46 should resolve the problem.

**Pull request closed without merging**
