### PR TITLE
Fixed Issue #18 Spawn non-blocking

### PR DESCRIPTION
**Pull request by demonfiddler**
Re-submitting changes, with async integration test now working across both Unix and Windows platforms. Also fixed some line-end issues.

My apologies for the profusion of commits, but to get this working on travis-ci I had to perform a succession of pushes.

Note: On travis-ci the async integration test works fine on OracleJDK-1.7 and OracleJDK-1.8 but I was unable to get it working on OpenJDK-1.6, so it's now skipped on that JDK. The test also works fine on Ubuntu-15.10 with OpenJDK-1.7 and Windows 8 with OracleJDK-1.7.

P.S. I'll be away from work for the next 10 days, so unable to respond in the interim.

### CODE REVIEW

**Comment by demonfiddler** [comment]
6 weeks elapsed... any chance of a response?

**Comment by khmarbaise** [comment]
Would it be possible to squash the changes otherwise it is more or less impossible to see what really has changed...And why does the test fail on OpenJDK 6 ? On Oracle JDK 6 as well ? (yes 6 weeks but i'm working on this if i have the time for it)..

**Comment by demonfiddler** [comment]
Thanks for the response Karl.

The test failed on OpenJDK-1.6 because something (don't recall what, certainly not any of my code, not directly at any rate) was trying to invoke some com.sun.* class that doesn't exist in OpenJDK. For reasons unknown this problem didn't manifest on OpenJDK-1.7. As for Oracle JDK 1.6 - as I recall it Travis is not configured to test on that JVM, so I do not know. Based on the reason for the failure on OpenJDK I'd expect it to pass.

I'm not familiar with squashing, looks complicated, will have to research.

**Comment by khmarbaise** [comment]
That sounds like i should change the configuration to run on OpenJDK 6 ...to check that cause com.sun.* is never a good idea...

**Comment by demonfiddler** [comment]
I'm confused - the Travis configuration **already** included OpenJDK 6 and in order for that to pass overall I had to configure **just** the async test to skip OpenJDK 6. Did you mean that you should change the configuration to include **Oracle JDK 6**?

Regarding rebase/squash, I've spent hours watching tutorials, reading docs, scratching my head and experimenting, to no avail. I'm totally confused by the concept - or at least I can't seem to get it to work. I haven't been able to figure out what sequence of commands and options I would have to issue to squash the commits in question, since some of them occurred on master and were then pushed and others occurred on a build-debug branch and were then pushed, to trigger the Travis build, and were subsequently merged into master and then pushed. I really have no idea how to proceed and I don't have access to a Git expert for help.

Regarding reviewing the changes, although the PR includes some 18 commits, it nevertheless seems possible to view an integrated file-by-file diff on GitHub simply by clicking the [Files changed link](https://github.com/mojohaus/exec-maven-plugin/pull/21/files) above - is that sufficient for reviewing purposes?

**Comment by demonfiddler** [comment]
Karl, I finally figured out how to squash my commits, so now you have just a single, conflict-less commit to review and merge. Thanks!

**Comment by demonfiddler** [comment]
Thanks for the merge, Karl.

**Pull request merged**
